// This file is generated by Ember Desktop.  Please do not edit manually.
//
//

// This file contains the tokens for attributes stored in flash


// Identifier tags for tokens
// Creator for attribute: ZCL version, singleton.
#define CREATOR_VERSION_SINGLETON 0xB000
// Creator for attribute: application version, singleton.
#define CREATOR_APPLICATION_VERSION_SINGLETON 0xB001
// Creator for attribute: stack version, singleton.
#define CREATOR_STACK_VERSION_SINGLETON 0xB002
// Creator for attribute: hardware version, singleton.
#define CREATOR_HW_VERSION_SINGLETON 0xB003
// Creator for attribute: manufacturer name, singleton.
#define CREATOR_MANUFACTURER_NAME_SINGLETON 0xB004
// Creator for attribute: model identifier, singleton.
#define CREATOR_MODEL_IDENTIFIER_SINGLETON 0xB005
// Creator for attribute: date code, singleton.
#define CREATOR_DATE_CODE_SINGLETON 0xB006
// Creator for attribute: power source, singleton.
#define CREATOR_POWER_SOURCE_SINGLETON 0xB007
// Creator for attribute: on/off, endpoint: 1
#define CREATOR_ON_OFF_1 0xB008
// Creator for attribute: current summation delivered, endpoint: 1
#define CREATOR_CURRENT_SUMMATION_DELIVERED_1 0xB009
// Creator for MAX71020: calibration parameter
#define CREATOR_MAX71020_AFE_PARAMTER   0xB00A

// Types for the tokens
#ifdef DEFINETYPES
typedef uint8_t  tokType_version;
typedef uint8_t  tokType_application_version;
typedef uint8_t  tokType_stack_version;
typedef uint8_t  tokType_hw_version;
typedef uint8_t  tokType_manufacturer_name[33];
typedef uint8_t  tokType_model_identifier[33];
typedef uint8_t  tokType_date_code[17];
typedef uint8_t  tokType_power_source;
typedef uint8_t  tokType_current_summation_delivered[6];
typedef uint8_t  tokType_on_off;
typedef uint8_t  tokType_max71020_afe_paramter[36];

#endif // DEFINETYPES


// Actual token definitions
#ifdef DEFINETOKENS
DEFINE_BASIC_TOKEN(VERSION_SINGLETON, tokType_version, 0x02)
DEFINE_BASIC_TOKEN(APPLICATION_VERSION_SINGLETON, tokType_application_version, 0x01)
DEFINE_BASIC_TOKEN(STACK_VERSION_SINGLETON, tokType_stack_version, 0x01)
DEFINE_BASIC_TOKEN(HW_VERSION_SINGLETON, tokType_hw_version, 0x01)
DEFINE_BASIC_TOKEN(MANUFACTURER_NAME_SINGLETON, tokType_manufacturer_name, {6,'W','u','l','i','a','n',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0})
DEFINE_BASIC_TOKEN(MODEL_IDENTIFIER_SINGLETON, tokType_model_identifier, {6,'T','-','C','Z','0','X',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0})
DEFINE_BASIC_TOKEN(DATE_CODE_SINGLETON, tokType_date_code, {8,'2','0','1','6','0','3','1','7',0,0,0,0,0,0,0,0})
DEFINE_BASIC_TOKEN(POWER_SOURCE_SINGLETON, tokType_power_source, 0x01)
DEFINE_BASIC_TOKEN(ON_OFF_1, tokType_on_off, 0x00)
DEFINE_BASIC_TOKEN(CURRENT_SUMMATION_DELIVERED_1, tokType_current_summation_delivered, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00})
DEFINE_BASIC_TOKEN(MAX71020_AFE_PARAMTER, tokType_max71020_afe_paramter, {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0})
#endif // DEFINETOKENS


// Macro snippet that loads all the attributes from tokens
#define GENERATED_TOKEN_LOADER(endpoint) do {\
  uint8_t ptr[33]; \
  uint8_t curNetwork = emberGetCurrentNetwork(); \
  uint8_t epNetwork; \
  halCommonGetToken((tokType_version *)ptr, TOKEN_VERSION_SINGLETON); \
  emberAfWriteServerAttribute(1, ZCL_BASIC_CLUSTER_ID, ZCL_VERSION_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
  halCommonGetToken((tokType_application_version *)ptr, TOKEN_APPLICATION_VERSION_SINGLETON); \
  emberAfWriteServerAttribute(1, ZCL_BASIC_CLUSTER_ID, ZCL_APPLICATION_VERSION_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
  halCommonGetToken((tokType_stack_version *)ptr, TOKEN_STACK_VERSION_SINGLETON); \
  emberAfWriteServerAttribute(1, ZCL_BASIC_CLUSTER_ID, ZCL_STACK_VERSION_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
  halCommonGetToken((tokType_hw_version *)ptr, TOKEN_HW_VERSION_SINGLETON); \
  emberAfWriteServerAttribute(1, ZCL_BASIC_CLUSTER_ID, ZCL_HW_VERSION_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
  halCommonGetToken((tokType_manufacturer_name *)ptr, TOKEN_MANUFACTURER_NAME_SINGLETON); \
  emberAfWriteServerAttribute(1, ZCL_BASIC_CLUSTER_ID, ZCL_MANUFACTURER_NAME_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_CHAR_STRING_ATTRIBUTE_TYPE); \
  halCommonGetToken((tokType_model_identifier *)ptr, TOKEN_MODEL_IDENTIFIER_SINGLETON); \
  emberAfWriteServerAttribute(1, ZCL_BASIC_CLUSTER_ID, ZCL_MODEL_IDENTIFIER_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_CHAR_STRING_ATTRIBUTE_TYPE); \
  halCommonGetToken((tokType_date_code *)ptr, TOKEN_DATE_CODE_SINGLETON); \
  emberAfWriteServerAttribute(1, ZCL_BASIC_CLUSTER_ID, ZCL_DATE_CODE_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_CHAR_STRING_ATTRIBUTE_TYPE); \
  halCommonGetToken((tokType_power_source *)ptr, TOKEN_POWER_SOURCE_SINGLETON); \
  emberAfWriteServerAttribute(1, ZCL_BASIC_CLUSTER_ID, ZCL_POWER_SOURCE_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_ENUM8_ATTRIBUTE_TYPE); \
  epNetwork = emberAfNetworkIndexFromEndpoint(1); \
  if((endpoint) == 1 || ((endpoint) == EMBER_BROADCAST_ENDPOINT && epNetwork == curNetwork)) { \
    halCommonGetToken((tokType_on_off *)ptr, TOKEN_ON_OFF_1); \
    emberAfWriteServerAttribute(1, ZCL_ON_OFF_CLUSTER_ID, ZCL_ON_OFF_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_BOOLEAN_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_current_summation_delivered *)ptr, TOKEN_CURRENT_SUMMATION_DELIVERED_1); \
    emberAfWriteServerAttribute(1, ZCL_SIMPLE_METERING_CLUSTER_ID, ZCL_CURRENT_SUMMATION_DELIVERED_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_INT48U_ATTRIBUTE_TYPE); \
  } \
} while(false)


// Macro snippet that saves the attribute to token
#define GENERATED_TOKEN_SAVER do {\
  uint8_t allZeroData[33]; \
  MEMSET(allZeroData, 0, 33); \
  if ( data == NULL ) data = allZeroData; \
  if ( clusterId == 0x00 ) { \
    if ( metadata->attributeId == 0x0000 && !emberAfAttributeIsClient(metadata) ) \
      halCommonSetToken(TOKEN_VERSION_SINGLETON, data); \
    if ( metadata->attributeId == 0x0001 && !emberAfAttributeIsClient(metadata) ) \
      halCommonSetToken(TOKEN_APPLICATION_VERSION_SINGLETON, data); \
    if ( metadata->attributeId == 0x0002 && !emberAfAttributeIsClient(metadata) ) \
      halCommonSetToken(TOKEN_STACK_VERSION_SINGLETON, data); \
    if ( metadata->attributeId == 0x0003 && !emberAfAttributeIsClient(metadata) ) \
      halCommonSetToken(TOKEN_HW_VERSION_SINGLETON, data); \
    if ( metadata->attributeId == 0x0004 && !emberAfAttributeIsClient(metadata) ) \
      halCommonSetToken(TOKEN_MANUFACTURER_NAME_SINGLETON, data); \
    if ( metadata->attributeId == 0x0005 && !emberAfAttributeIsClient(metadata) ) \
      halCommonSetToken(TOKEN_MODEL_IDENTIFIER_SINGLETON, data); \
    if ( metadata->attributeId == 0x0006 && !emberAfAttributeIsClient(metadata) ) \
      halCommonSetToken(TOKEN_DATE_CODE_SINGLETON, data); \
    if ( metadata->attributeId == 0x0007 && !emberAfAttributeIsClient(metadata) ) \
      halCommonSetToken(TOKEN_POWER_SOURCE_SINGLETON, data); \
  }\
  if ( endpoint == 1 ) { \
    if ( clusterId == 0x06 ) { \
      if ( metadata->attributeId == 0x0000 && !emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_ON_OFF_1, data); \
    } else if ( clusterId == 0x0702 ) { \
      if ( metadata->attributeId == 0x0000 && !emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_CURRENT_SUMMATION_DELIVERED_1, data); \
    } \
  } \
} while(false)


